<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>

    <!-- BepInEx -->
    <Reference Include="BepInEx">
      <HintPath>lib\BepInEx.dll</HintPath>
    </Reference>

    <Reference Include="0Harmony">
      <HintPath>lib\0Harmony.dll</HintPath>
    </Reference>

    <!-- Unity -->
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>lib\UnityEngine.CoreModule.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>lib\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>

    <!-- Game code -->
    <Reference Include="Assembly-CSharp">
      <HintPath>lib\Assembly-CSharp.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine">
      <HintPath>lib\UnityEngine.dll</HintPath>
    </Reference>

    <Reference Include="Unity.InputSystem">
      <HintPath>lib\Unity.InputSystem.dll</HintPath>
    </Reference>

  </ItemGroup>

</Project>